if (BUILD_STATIC)
    set(LIBGPIOD_LIB libgpiod.a gpiod)
else ()
    set(LIBGPIOD_LIB gpiod)
endif ()

find_library(HAVE_LIBGPIOD NAMES ${LIBGPIOD_LIB})
if (HAVE_LIBGPIOD)
    set(LIB_LIBGPIOD ${HAVE_LIBGPIOD})
    message(STATUS "libgpiod found: ${LIB_LIBGPIOD}")
    set(CMAKE_REQUIRED_LIBRARIES ${LIB_LIBGPIOD})
else ()
    message(FATAL_ERROR "libgpiod not found")
endif ()
